### ISSUE TITLE
Error fitting model system is computationally singular

### ISSUE THREAD

**Issue by antgomo** [ziyili20/TOAST#2]
When i am trying to fit the model to my RNAseq counts matrix i got

_Error in solve.default(t(W) %*% W) : 
  system is computationally singular: reciprocal condition number = 1.16781e-24_

This is my code

    Design_out <- makeDesign(design, Prop)

    fitted_model <- fitModel(Design_out, y$counts)

**Comment by ziyili20** [comment]
This error basically tells us the linear system is unsolvable because the design matrix is singular. This happens when there are too many covariates to adjust for, or some columns in Prop matrix is all zero, or collinearity exists in Prop matrix. 

One solution is to check the Prop matrix and the covariates. Take my own experience as an example. There is a time that I built a model adjusting for age and disease status, but the model became singular. After removing age variable, the model can work properly again.

Hope this helps.
